// Code generated by protoc-gen-gogo.
// source: gogo.proto
// DO NOT EDIT!

/*
Package gogoproto is a generated protocol buffer package.

It is generated from these files:
	gogo.proto

It has these top-level messages:
	FieldBinding
*/
package gogoproto

import proto "github.com/nourish/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/nourish/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type FieldBinding struct {
	Ignore           *bool   `protobuf:"varint,1,opt,name=ignore" json:"ignore,omitempty"`
	Required         *bool   `protobuf:"varint,2,opt,name=required" json:"required,omitempty"`
	ValidRegex       *string `protobuf:"bytes,3,opt,name=valid_regex,json=validRegex" json:"valid_regex,omitempty"`
	IntGt            *int64  `protobuf:"varint,4,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	IntGte           *int64  `protobuf:"varint,5,opt,name=int_gte,json=intGte" json:"int_gte,omitempty"`
	IntLt            *int64  `protobuf:"varint,6,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	IntLte           *int64  `protobuf:"varint,7,opt,name=int_lte,json=intLte" json:"int_lte,omitempty"`
	MaxLen           *int64  `protobuf:"varint,8,opt,name=max_len,json=maxLen" json:"max_len,omitempty"`
	MinLen           *int64  `protobuf:"varint,9,opt,name=min_len,json=minLen" json:"min_len,omitempty"`
	InvalidMessage   *string `protobuf:"bytes,10,opt,name=invalid_message,json=invalidMessage" json:"invalid_message,omitempty"`
	CustomBinder     *string `protobuf:"bytes,11,opt,name=custom_binder,json=customBinder" json:"custom_binder,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FieldBinding) Reset()                    { *m = FieldBinding{} }
func (m *FieldBinding) String() string            { return proto.CompactTextString(m) }
func (*FieldBinding) ProtoMessage()               {}
func (*FieldBinding) Descriptor() ([]byte, []int) { return fileDescriptorGogo, []int{0} }

func (m *FieldBinding) GetIgnore() bool {
	if m != nil && m.Ignore != nil {
		return *m.Ignore
	}
	return false
}

func (m *FieldBinding) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *FieldBinding) GetValidRegex() string {
	if m != nil && m.ValidRegex != nil {
		return *m.ValidRegex
	}
	return ""
}

func (m *FieldBinding) GetIntGt() int64 {
	if m != nil && m.IntGt != nil {
		return *m.IntGt
	}
	return 0
}

func (m *FieldBinding) GetIntGte() int64 {
	if m != nil && m.IntGte != nil {
		return *m.IntGte
	}
	return 0
}

func (m *FieldBinding) GetIntLt() int64 {
	if m != nil && m.IntLt != nil {
		return *m.IntLt
	}
	return 0
}

func (m *FieldBinding) GetIntLte() int64 {
	if m != nil && m.IntLte != nil {
		return *m.IntLte
	}
	return 0
}

func (m *FieldBinding) GetMaxLen() int64 {
	if m != nil && m.MaxLen != nil {
		return *m.MaxLen
	}
	return 0
}

func (m *FieldBinding) GetMinLen() int64 {
	if m != nil && m.MinLen != nil {
		return *m.MinLen
	}
	return 0
}

func (m *FieldBinding) GetInvalidMessage() string {
	if m != nil && m.InvalidMessage != nil {
		return *m.InvalidMessage
	}
	return ""
}

func (m *FieldBinding) GetCustomBinder() string {
	if m != nil && m.CustomBinder != nil {
		return *m.CustomBinder
	}
	return ""
}

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix,json=goprotoEnumPrefix",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gogoproto.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer,json=goprotoEnumStringer",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gogoproto.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer,json=enumStringer",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gogoproto.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname,json=enumCustomname",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gogoproto.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname,json=enumvalueCustomname",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gogoproto.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all,json=goprotoGettersAll",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gogoproto.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all,json=goprotoEnumPrefixAll",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gogoproto.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all,json=goprotoStringerAll",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gogoproto.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all,json=verboseEqualAll",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gogoproto.face_all",
	Tag:           "varint,63005,opt,name=face_all,json=faceAll",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gogoproto.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all,json=gostringAll",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gogoproto.populate_all",
	Tag:           "varint,63007,opt,name=populate_all,json=populateAll",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gogoproto.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all,json=stringerAll",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gogoproto.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all,json=onlyoneAll",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gogoproto.equal_all",
	Tag:           "varint,63013,opt,name=equal_all,json=equalAll",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gogoproto.description_all",
	Tag:           "varint,63014,opt,name=description_all,json=descriptionAll",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gogoproto.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all,json=testgenAll",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gogoproto.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all,json=benchgenAll",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gogoproto.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all,json=marshalerAll",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gogoproto.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all,json=unmarshalerAll",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gogoproto.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all,json=stableMarshalerAll",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gogoproto.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all,json=sizerAll",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gogoproto.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all,json=goprotoEnumStringerAll",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gogoproto.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all,json=enumStringerAll",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gogoproto.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all,json=unsafeMarshalerAll",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gogoproto.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all,json=unsafeUnmarshalerAll",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gogoproto.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all,json=goprotoExtensionsMapAll",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gogoproto.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all,json=goprotoUnrecognizedAll",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gogoproto.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import,json=gogoprotoImport",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gogoproto.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all,json=protosizerAll",
}

var E_BindingEnabledAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gogoproto.binding_enabled_all",
	Tag:           "varint,63029,opt,name=binding_enabled_all,json=bindingEnabledAll",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gogoproto.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters,json=goprotoGetters",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gogoproto.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer,json=goprotoStringer",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gogoproto.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal,json=verboseEqual",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gogoproto.face",
	Tag:           "varint,64005,opt,name=face",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gogoproto.gostring",
	Tag:           "varint,64006,opt,name=gostring",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gogoproto.populate",
	Tag:           "varint,64007,opt,name=populate",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gogoproto.stringer",
	Tag:           "varint,67008,opt,name=stringer",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gogoproto.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gogoproto.equal",
	Tag:           "varint,64013,opt,name=equal",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gogoproto.description",
	Tag:           "varint,64014,opt,name=description",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gogoproto.testgen",
	Tag:           "varint,64015,opt,name=testgen",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gogoproto.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gogoproto.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gogoproto.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gogoproto.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler,json=stableMarshaler",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gogoproto.sizer",
	Tag:           "varint,64020,opt,name=sizer",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gogoproto.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler,json=unsafeMarshaler",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gogoproto.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler,json=unsafeUnmarshaler",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gogoproto.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map,json=goprotoExtensionsMap",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gogoproto.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized,json=goprotoUnrecognized",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gogoproto.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
}

var E_BindingEnabled = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gogoproto.binding_enabled",
	Tag:           "varint,64029,opt,name=binding_enabled,json=bindingEnabled",
}

var E_ValidationEnabled = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gogoproto.validation_enabled",
	Tag:           "varint,64030,opt,name=validation_enabled,json=validationEnabled",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gogoproto.nullable",
	Tag:           "varint,65001,opt,name=nullable",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gogoproto.embed",
	Tag:           "varint,65002,opt,name=embed",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gogoproto.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gogoproto.customname",
	Tag:           "bytes,65004,opt,name=customname",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gogoproto.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gogoproto.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gogoproto.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gogoproto.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gogoproto.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
}

var E_Binding = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*FieldBinding)(nil),
	Field:         65010,
	Name:          "gogoproto.binding",
	Tag:           "bytes,65010,opt,name=binding",
}

var E_Skip = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65011,
	Name:          "gogoproto.skip",
	Tag:           "varint,65011,opt,name=skip",
}

func init() {
	proto.RegisterType((*FieldBinding)(nil), "gogoproto.FieldBinding")
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_BindingEnabledAll)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_BindingEnabled)
	proto.RegisterExtension(E_ValidationEnabled)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
	proto.RegisterExtension(E_Binding)
	proto.RegisterExtension(E_Skip)
}

var fileDescriptorGogo = []byte{
	// 1343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x98, 0xcb, 0x6f, 0x1b, 0x45,
	0x18, 0xc0, 0xd5, 0xe6, 0x61, 0xfb, 0xb3, 0x93, 0x90, 0x4d, 0x9a, 0x98, 0x08, 0xd4, 0x16, 0x0e,
	0x70, 0x72, 0x25, 0x10, 0x42, 0xdd, 0x08, 0xa1, 0xa6, 0x4a, 0xa2, 0xa2, 0x04, 0x22, 0x43, 0x0a,
	0x88, 0x83, 0xb5, 0xb6, 0x27, 0xdb, 0xa5, 0xeb, 0x1d, 0xb3, 0xbb, 0xae, 0x12, 0x6e, 0xa8, 0x3c,
	0x84, 0x10, 0x6f, 0x24, 0x68, 0x69, 0x0b, 0x1c, 0x78, 0x3f, 0xcb, 0xe3, 0x8e, 0x84, 0x80, 0x33,
	0xff, 0x43, 0x2f, 0x40, 0x79, 0xe7, 0x96, 0x0b, 0x33, 0xb3, 0xdf, 0xb7, 0x5e, 0x3b, 0x96, 0x66,
	0x7c, 0xf3, 0xce, 0xcc, 0xef, 0x97, 0xd9, 0xef, 0xdb, 0xf9, 0xbe, 0xdd, 0x00, 0xb8, 0xdc, 0xe5,
	0x95, 0x76, 0xc8, 0x63, 0x6e, 0x15, 0xe4, 0x6f, 0xf5, 0x73, 0xe1, 0x88, 0xcb, 0xb9, 0xeb, 0xb3,
	0x63, 0xea, 0xaa, 0xde, 0xd9, 0x3a, 0xd6, 0x64, 0x51, 0x23, 0xf4, 0xda, 0x31, 0x0f, 0x93, 0xc5,
	0xb7, 0xfc, 0x70, 0x10, 0x4a, 0x2b, 0x1e, 0xf3, 0x9b, 0x4b, 0x5e, 0xd0, 0xf4, 0x02, 0xd7, 0x9a,
	0x83, 0x71, 0xcf, 0x0d, 0x78, 0xc8, 0xca, 0x07, 0x8e, 0x1c, 0xb8, 0x3d, 0x5f, 0xc5, 0x2b, 0x6b,
	0x01, 0xf2, 0x21, 0x7b, 0xa2, 0xe3, 0x85, 0xac, 0x59, 0x3e, 0xa8, 0x66, 0xd2, 0x6b, 0xeb, 0x30,
	0x14, 0xcf, 0x39, 0xbe, 0xd7, 0xac, 0x85, 0xcc, 0x65, 0xdb, 0xe5, 0x11, 0x31, 0x5d, 0xa8, 0x82,
	0x1a, 0xaa, 0xca, 0x11, 0xeb, 0x90, 0x90, 0x06, 0x71, 0xcd, 0x8d, 0xcb, 0xa3, 0x62, 0x6e, 0xa4,
	0x3a, 0x26, 0xae, 0x56, 0x63, 0x6b, 0x1e, 0x72, 0xc9, 0x30, 0x2b, 0x8f, 0xa9, 0xf1, 0x71, 0x35,
	0xce, 0x68, 0xbd, 0x1f, 0x97, 0xc7, 0xd3, 0xf5, 0x6b, 0xe9, 0x7a, 0x5f, 0xac, 0xcf, 0xa5, 0xeb,
	0xd7, 0xc4, 0x7a, 0x31, 0xd1, 0x72, 0xb6, 0x6b, 0x3e, 0x0b, 0xca, 0xf9, 0x64, 0x42, 0x5c, 0xae,
	0xb1, 0x40, 0x4d, 0x78, 0x81, 0x9a, 0x28, 0xe0, 0x84, 0x17, 0xc8, 0x89, 0xdb, 0x60, 0xca, 0x0b,
	0x92, 0x4d, 0xb7, 0x58, 0x14, 0x39, 0x2e, 0x2b, 0x83, 0xda, 0xf6, 0x24, 0x0e, 0xaf, 0x27, 0xa3,
	0xd6, 0xad, 0x30, 0xd1, 0xe8, 0x44, 0x31, 0x6f, 0xd5, 0xea, 0x22, 0x42, 0x2c, 0x2c, 0x17, 0xd5,
	0xb2, 0x52, 0x32, 0xb8, 0xa4, 0xc6, 0xec, 0xfb, 0x61, 0x06, 0x43, 0x5e, 0x63, 0x41, 0xa7, 0x55,
	0x6b, 0x87, 0x6c, 0xcb, 0xdb, 0xb6, 0x6e, 0xaa, 0x24, 0xf1, 0xaf, 0x50, 0xfc, 0x2b, 0xcb, 0x62,
	0xf6, 0x81, 0x76, 0xec, 0xf1, 0x20, 0x2a, 0x5f, 0xbd, 0x36, 0xa2, 0xe2, 0x38, 0x8d, 0xa8, 0x9c,
	0xdb, 0x50, 0xa0, 0x5d, 0x85, 0x43, 0x3d, 0xbe, 0x28, 0x0e, 0x45, 0x6e, 0x58, 0xa8, 0x31, 0xfe,
	0x88, 0xc6, 0x99, 0x8c, 0xf1, 0x41, 0x44, 0xed, 0x93, 0x30, 0x31, 0x8c, 0xeb, 0x27, 0x74, 0x95,
	0x58, 0x56, 0xb2, 0x0a, 0x53, 0x4a, 0x92, 0xdc, 0x7d, 0xe0, 0xb4, 0x98, 0x46, 0xf3, 0xf3, 0xb5,
	0xe4, 0x69, 0x98, 0x94, 0xd8, 0xc9, 0x94, 0xb2, 0x4f, 0xc3, 0xac, 0x1c, 0x11, 0xa1, 0xee, 0xb0,
	0xac, 0xed, 0xe8, 0x40, 0xdb, 0x69, 0xb9, 0x8c, 0x94, 0xbf, 0x9c, 0x1f, 0x55, 0xca, 0x99, 0x54,
	0x90, 0xf1, 0x66, 0x32, 0xe1, 0xb2, 0x38, 0x66, 0x61, 0x54, 0x73, 0x7c, 0x7f, 0xc0, 0x26, 0x57,
	0x3c, 0x3f, 0x35, 0x5e, 0xb8, 0xde, 0x9b, 0x89, 0xd5, 0x84, 0x3c, 0xe1, 0xfb, 0xf6, 0x26, 0xcc,
	0x0f, 0xc8, 0xac, 0x81, 0xf3, 0x22, 0x3a, 0x67, 0xf7, 0x65, 0x57, 0x6a, 0x37, 0x80, 0xc6, 0xd3,
	0x7c, 0x18, 0x38, 0xdf, 0x46, 0xa7, 0x85, 0x2c, 0xa5, 0x45, 0x1a, 0xef, 0x83, 0xe9, 0x73, 0x2c,
	0xac, 0xf3, 0x88, 0xd5, 0xc4, 0xb1, 0x74, 0x7c, 0x03, 0xdd, 0x25, 0xd4, 0x4d, 0x21, 0xb8, 0x2c,
	0x39, 0xe9, 0x3a, 0x0e, 0xf9, 0x2d, 0xa7, 0xc1, 0x0c, 0x14, 0x97, 0x51, 0x91, 0x93, 0xeb, 0x25,
	0x7a, 0x02, 0x4a, 0x2e, 0x4f, 0x6e, 0xc9, 0x00, 0xbf, 0x82, 0x78, 0x91, 0x18, 0x54, 0xb4, 0x79,
	0xbb, 0xe3, 0x3b, 0xb1, 0xc9, 0x0e, 0xde, 0x21, 0x05, 0x31, 0xa8, 0x18, 0x22, 0xac, 0xef, 0x92,
	0x22, 0xca, 0xc4, 0xf3, 0x5e, 0x28, 0xf2, 0xc0, 0xdf, 0xe1, 0x81, 0xc9, 0x26, 0xde, 0x43, 0x03,
	0x20, 0x22, 0x05, 0x8b, 0x50, 0x30, 0x4d, 0xc4, 0xfb, 0x88, 0xe7, 0x19, 0x65, 0x40, 0x9c, 0x33,
	0x2a, 0xd5, 0x62, 0x85, 0x81, 0xe2, 0x03, 0x54, 0x4c, 0x66, 0x30, 0xbc, 0x8d, 0x98, 0x45, 0xb1,
	0xcb, 0x4c, 0x24, 0x1f, 0xd2, 0x6d, 0x20, 0x82, 0xa1, 0xac, 0xb3, 0xa0, 0x71, 0xc6, 0xcc, 0xf0,
	0x11, 0x85, 0x92, 0x18, 0xa9, 0x10, 0x95, 0xa7, 0xe5, 0x84, 0xd1, 0x19, 0xc7, 0x37, 0x4a, 0xc7,
	0xc7, 0xe8, 0x28, 0xa5, 0x10, 0x46, 0xa4, 0x13, 0x0c, 0xa3, 0xf9, 0x84, 0x22, 0x92, 0xc1, 0xf0,
	0xe8, 0x45, 0xb1, 0x53, 0xf7, 0x59, 0x6d, 0x18, 0xdb, 0xa7, 0x74, 0xf4, 0x12, 0x76, 0x3d, 0x6b,
	0x14, 0x99, 0x8e, 0xbc, 0x27, 0x8d, 0x34, 0x9f, 0x51, 0xa6, 0x15, 0x20, 0xe1, 0x47, 0xe1, 0xc6,
	0x81, 0xa5, 0xde, 0x40, 0xf6, 0x39, 0xca, 0xe6, 0x06, 0x94, 0x7b, 0x2c, 0x09, 0xc3, 0x2a, 0xbf,
	0xa0, 0x92, 0xc0, 0xfa, 0x5c, 0x22, 0x6a, 0x9d, 0x20, 0x72, 0xb6, 0x86, 0x8b, 0xda, 0x97, 0x14,
	0xb5, 0x84, 0xed, 0x89, 0xda, 0x43, 0x30, 0x87, 0xc6, 0xe1, 0xf2, 0xfa, 0x15, 0x15, 0xd6, 0x84,
	0xde, 0xec, 0xcd, 0xee, 0x63, 0xb0, 0x90, 0x86, 0x73, 0x3b, 0x66, 0x41, 0x24, 0x19, 0xb1, 0xe7,
	0xb6, 0x81, 0xf9, 0x2a, 0x9a, 0xa9, 0xe2, 0x2f, 0xa7, 0x82, 0x75, 0xa7, 0x2d, 0xe5, 0x8f, 0x40,
	0x99, 0xe4, 0x9d, 0x20, 0x64, 0x0d, 0xee, 0x06, 0x22, 0x8d, 0x4d, 0x03, 0xf5, 0xd7, 0x7d, 0xa9,
	0xda, 0xcc, 0xe0, 0xd2, 0x7c, 0x0a, 0x6e, 0x48, 0xdf, 0xda, 0x6a, 0x5e, 0xab, 0xcd, 0xc3, 0x58,
	0x63, 0xfc, 0x86, 0x32, 0x95, 0x72, 0xa7, 0x14, 0x66, 0x2f, 0xc3, 0xa4, 0xba, 0x34, 0x7d, 0x24,
	0xbf, 0x45, 0xd1, 0x44, 0x97, 0x92, 0x3b, 0x12, 0x8d, 0xb4, 0x9e, 0xbc, 0x12, 0x8a, 0xe7, 0x52,
	0x3e, 0xf2, 0x26, 0xb7, 0xf9, 0x1d, 0x35, 0x52, 0x44, 0x97, 0x13, 0x32, 0x79, 0x18, 0xa7, 0xfa,
	0x1a, 0xb3, 0x75, 0x78, 0x9f, 0x0b, 0x5f, 0xba, 0x48, 0xf7, 0xd4, 0x2e, 0x1e, 0xe1, 0xde, 0xbe,
	0x6c, 0xaf, 0xc9, 0x68, 0xf5, 0x76, 0x4f, 0xbd, 0xec, 0xfc, 0x6e, 0x1a, 0xb0, 0x9e, 0xe6, 0x69,
	0xaf, 0xc0, 0x44, 0x4f, 0xe7, 0xd4, 0xab, 0x9e, 0x46, 0x55, 0x29, 0xdb, 0x38, 0xed, 0xbb, 0x60,
	0x54, 0x76, 0x41, 0x3d, 0xfe, 0x0c, 0xe2, 0x6a, 0xb9, 0x7d, 0x0f, 0xe4, 0xa9, 0xfb, 0xe9, 0xd1,
	0x67, 0x11, 0x4d, 0x11, 0x89, 0x53, 0xe7, 0xd3, 0xe3, 0xcf, 0x11, 0x4e, 0x88, 0xc4, 0xcd, 0x43,
	0xf8, 0xfd, 0x0b, 0xa3, 0x58, 0xbd, 0x28, 0x76, 0x8b, 0x90, 0xc3, 0x96, 0xa7, 0xa7, 0x9f, 0xc7,
	0x3f, 0x4e, 0x84, 0x7d, 0x37, 0x8c, 0x19, 0x06, 0xfc, 0x45, 0x44, 0x93, 0xf5, 0xa2, 0xa1, 0x14,
	0x33, 0x6d, 0x4e, 0x8f, 0xbf, 0x84, 0x78, 0x96, 0x92, 0x5b, 0xc7, 0x36, 0xa7, 0x17, 0xbc, 0x4c,
	0x5b, 0x47, 0x42, 0x86, 0x8d, 0x3a, 0x9c, 0x9e, 0x7e, 0x85, 0xa2, 0x4e, 0x88, 0xe8, 0xca, 0x85,
	0xb4, 0x6a, 0xe9, 0xf9, 0x57, 0x91, 0xef, 0x32, 0x32, 0x02, 0x99, 0xaa, 0xa9, 0x57, 0xbc, 0x46,
	0x11, 0xc8, 0x50, 0xf2, 0x18, 0xf5, 0x77, 0x42, 0xbd, 0xe9, 0x75, 0x3a, 0x46, 0x7d, 0x8d, 0x50,
	0x66, 0x53, 0x15, 0x0f, 0xbd, 0xe2, 0x0d, 0xca, 0xa6, 0x5a, 0x2f, 0xb7, 0xd1, 0xdf, 0x5a, 0xf4,
	0x8e, 0x37, 0x69, 0x1b, 0x7d, 0x9d, 0x45, 0x34, 0x2a, 0x6b, 0x7f, 0x5b, 0xd1, 0xfb, 0xde, 0x42,
	0xdf, 0xf4, 0xbe, 0xae, 0x62, 0x3f, 0x0c, 0x73, 0x83, 0x5b, 0x8a, 0xde, 0x7a, 0x61, 0xb7, 0xef,
	0x23, 0x20, 0xdb, 0x51, 0x44, 0x07, 0x9c, 0x1d, 0xd4, 0x4e, 0xf4, 0xda, 0x8b, 0xbb, 0xbd, 0xdf,
	0x79, 0xd9, 0x6e, 0x22, 0x5e, 0xd8, 0xa0, 0x5b, 0xc9, 0xf5, 0xae, 0x4b, 0xe8, 0xca, 0x40, 0xb2,
	0x56, 0xf7, 0xd5, 0x7e, 0xbd, 0xe7, 0x32, 0xd5, 0xea, 0xde, 0xd2, 0x2f, 0xf3, 0xa1, 0xbe, 0xa7,
	0x1d, 0xf5, 0x22, 0x6b, 0xac, 0xbb, 0x42, 0xf9, 0xe8, 0xc2, 0x64, 0x5c, 0x84, 0x7c, 0xd0, 0xf1,
	0x7d, 0x79, 0x61, 0xdd, 0x3c, 0xa0, 0x1d, 0x31, 0xbf, 0x49, 0x96, 0x5f, 0xf7, 0xf0, 0xe4, 0x11,
	0x20, 0x8a, 0xf4, 0x18, 0x6b, 0xd5, 0xc5, 0x0e, 0x34, 0xe4, 0x6f, 0x7b, 0x54, 0x71, 0xe4, 0x6a,
	0x71, 0x60, 0x21, 0xf9, 0x48, 0x8d, 0x77, 0xda, 0xda, 0xbf, 0xfa, 0xfb, 0x1e, 0xfe, 0x07, 0xa4,
	0x8b, 0x74, 0x05, 0xea, 0x2b, 0x57, 0x23, 0xb8, 0xde, 0x2b, 0x50, 0x1f, 0xb6, 0xc7, 0x21, 0xf7,
	0x78, 0xc4, 0x83, 0xd8, 0x71, 0x75, 0xf4, 0x1f, 0x48, 0xd3, 0x7a, 0x19, 0xb0, 0x16, 0x0f, 0x99,
	0xf8, 0x19, 0xe9, 0xd8, 0x3f, 0x91, 0x4d, 0x01, 0x09, 0x37, 0x9c, 0x28, 0x36, 0xb9, 0xef, 0xbf,
	0x08, 0x26, 0x40, 0x6e, 0x5a, 0xfe, 0x3e, 0xcb, 0x76, 0x74, 0xec, 0xdf, 0xb4, 0x69, 0x5c, 0x2f,
	0x2a, 0x6c, 0x41, 0xfe, 0x54, 0xdf, 0xf7, 0x3a, 0xf8, 0x1f, 0x84, 0xbb, 0x84, 0x5d, 0x85, 0x1c,
	0x3e, 0x88, 0x3a, 0xf8, 0x5f, 0x05, 0x17, 0xef, 0x98, 0xaf, 0xa4, 0x6f, 0x52, 0x95, 0xec, 0x7f,
	0xc4, 0xaa, 0x24, 0xb2, 0xef, 0x84, 0xd1, 0xe8, 0xac, 0xd7, 0xd6, 0x09, 0xff, 0xc3, 0x47, 0x47,
	0x2d, 0x5e, 0x3a, 0x0a, 0x33, 0x0d, 0xde, 0xea, 0x27, 0x96, 0x60, 0x95, 0xaf, 0xf2, 0x0d, 0x75,
	0xe4, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x59, 0x54, 0x07, 0xf0, 0xbd, 0x13, 0x00, 0x00,
}
